"""Added reviews table

Revision ID: 6416ea68047d
Revises: b9f27cb8f542
Create Date: 2024-01-24 12:44:48.986111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6416ea68047d'
down_revision = 'b9f27cb8f542'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
                    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('reviewer_id', sa.BIGINT(), nullable=False),
                    sa.Column('reviewed_id', sa.BIGINT(), nullable=False),
                    sa.Column('task_id', sa.Integer(), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=False),
                    sa.Column('positive_sights', postgresql.ARRAY(sa.String()), nullable=True),
                    sa.Column('negative_sights', postgresql.ARRAY(sa.String()), nullable=True),
                    sa.Column('comment', sa.String(), nullable=True),
                    sa.Column('review_date', sa.TIMESTAMP(), nullable=True),
                    sa.ForeignKeyConstraint(['reviewed_id'], ['users.telegram_id'], ),
                    sa.ForeignKeyConstraint(['reviewer_id'], ['users.telegram_id'], ),
                    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
                    sa.PrimaryKeyConstraint('review_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
