"""Added field date_added for users

Revision ID: afb61f398ffa
Revises: 7294e99c26cb
Create Date: 2024-02-06 17:53:39.580060

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'afb61f398ffa'
down_revision = '7294e99c26cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_added', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_added')
    # ### end Alembic commands ###
