"""Changed unique constaraints for Chat model

Revision ID: b9f27cb8f542
Revises: c76350e284ff
Create Date: 2024-01-22 16:49:22.159956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f27cb8f542'
down_revision = 'c76350e284ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chats_chat_id_key', 'chats', type_='unique')
    op.drop_constraint('chats_supergroup_id_key', 'chats', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_unique_constraint('chats_supergroup_id_key', 'chats', ['supergroup_id'])
    op.create_unique_constraint('chats_chat_id_key', 'chats', ['chat_id'])

    # ### end Alembic commands ###
