"""Recreated tokenization for bank cards

Revision ID: eaf333b5e603
Revises: afb61f398ffa
Create Date: 2024-02-06 19:13:44.117767

"""
from alembic import op
import sqlalchemy as sa
from database.database import async_session
from sqlalchemy import update, table, column, select
from sqlalchemy.dialects import postgresql
from database.models import Balance
from utils.card_tokenization import encrypt_card_number

# revision identifiers, used by Alembic.
revision = 'eaf333b5e603'
down_revision = 'afb61f398ffa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('balance', 'user_cards',
                    existing_type=postgresql.ARRAY(sa.VARCHAR()),
                    type_=postgresql.ARRAY(sa.LargeBinary()),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('balance', 'user_cards',
                    existing_type=postgresql.ARRAY(sa.LargeBinary()),
                    type_=postgresql.ARRAY(sa.VARCHAR()),
                    existing_nullable=True)
    # ### end Alembic commands ###
